name: paleots
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.21.0
  - jupyter
  - climlab=0.7.13
  - pip
  - python=3.10
  - libstdcxx-ng=12.1.0
  - pip:
    - pyleoclim==0.10.0
    - pymannkendall
    - kneed
